spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.application.name=olympics
spring.datasource.url=jdbc:mysql://192.168.86.250:3310/olympics
spring.datasource.username=dev
spring.datasource.password=Bcjj4CsJ7469WHwBPVqa